[phases.setup]
aptPkgs = [
  "libglib2.0-0",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libxkbcommon0",
  "libatspi2.0-0",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "libgbm1",
  "libcairo2",
  "libpango-1.0-0",
  "libasound2",
  "libnss3",
  "libnspr4",
  "libdbus-1-3",
  "libx11-6",
  "libxext6",
  "libxcb1",
  "libexpat1"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    python -m playwright install chromium"
]
